name: Tests

on:
  push:
    branches:
    - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        version: [0.9.2]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Start dfs
      uses: ./
      with:
        version: ${{ matrix.version }}
      env:
        BEE: ${{secrets.BEE}}
        RPC: ${{secrets.RPC}}
        STAMP: ${{secrets.STAMP}}

    - name: Capture dfs version installed
      run: |
        export DFS_VERSION=$( dfs version )
        echo 'GH_VERSION_INSTALLED<<EOF' >> $GITHUB_ENV
        dfs version >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - name: Verify
      shell: python
      env:
        GH_VERSION_EXPECTED: ${{ matrix.version }}
      run: |
        import sys, os
        sys.exit(
            int(not os.environ["GH_VERSION_EXPECTED"] in os.environ["GH_VERSION_INSTALLED"])
        )