name: Tests

on:
  push:
    branches:
    - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        os: [macos-latest, windows-latest, ubuntu-latest]
        os: [ubuntu-latest]
        version: [0.9.2]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Start dfs
      uses: onepeerlabs/fdfs@v0.0.4
      with:
        version: ${{ matrix.version }}
        path: example/build/*
      env:
        BEE: ${{secrets.BEE}}
        RPC: ${{secrets.RPC}}
        STAMP: ${{secrets.STAMP}}
        USER_NAME: ${{secrets.USER_NAME}}
        PASSWORD: ${{secrets.PASSWORD}}
        POD: ${{secrets.POD}}
        ROOT: ${{secrets.ROOT}}